spring:
  data:
    mongodb:
      host: 10.254.5.61
logging:
  level:
    org:
      springframework:
        data: debug
        mongodb:
          core:
            MongoTemplate: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always